    Случайное число — это число, которое возникает в результате случайного процесса.

    Что такое случайный процесс? Например, это подбрасывание монетки. Может выпасть или орёл, или решка. Если, например, обозначить орла за 0, а решку — за 1, то в результате процесса подбрасывания монеты мы будем получать случайное число. Если подбросить монетку несколько раз, можно получить целый набор из случайных чисел, состоящий из 0 и 1. Аналогично можно подбрасывать кубик (игральную кость) и получать числа от 1 до 6. Случайным процессом можно назвать распространение инфекции, поскольку точное число новых заболевших за сутки остаётся непредсказуемым.

    Псевдослучайные числа — это такая последовательность чисел, которая возникает с помощью применения математических формул к какому-то исходному числу (например, текущему времени в микросекундах). Элементы, получаемые таким образом, почти не зависят друг от друга: например, при генерации следующего 0 или 1 не имеет значения, что выпало ранее — 0 или 1.

# Случайные числа в NumPy

## Генерация float

Для генерации псевдослучайных чисел в NumPy существует подмодуль random.

Самой «базовой» функцией в нём можно считать функцию rand. По умолчанию она генерирует число с плавающей точкой между 0 (включительно) и 1 (не включительно):

In [1]:
import numpy as np
np.random.rand()
# 0.06600758835806675

0.31020457429432446

    → Поскольку теперь мы работаем со случайными числами, не удивляйтесь, что вывод кода в примерах и на вашем компьютере может не совпадать.

Чтобы получить случайное число в диапазоне, например, от 0 до 100, достаточно просто умножить генерируемое число на 100:

In [2]:
np.random.rand() * 100
# 69.76076924077643

38.57691656256541

На самом деле rand умеет генерировать не только отдельные числа — функция принимает в качестве аргументов через запятую целые числа, которые задают форму генерируемого массива. Например, получим массив из пяти случайных чисел:

In [3]:
np.random.rand(5)
# array([0.83745099, 0.58426808, 0.89206204, 0.41149807, 0.42445145])

array([0.47883898, 0.73359888, 0.84130887, 0.40077788, 0.41574448])

Массив из двух случайных строк и трёх столбцов:

In [4]:
np.random.rand(2, 3)
# array([[0.94931212, 0.06680018, 0.26707599],
#      [0.67908873, 0.18001743, 0.97732239]])

array([[0.53009334, 0.05721195, 0.15320051],
       [0.5606608 , 0.09318255, 0.36244033]])

Функция rand может принимать неограниченное число целых чисел для задания формы массива:

In [5]:
np.random.rand(2, 3, 4, 10, 12, 23)

array([[[[[[6.84880371e-01, 9.58691439e-01, 7.19396625e-01, ...,
            2.93896564e-01, 1.85979686e-01, 6.97817857e-01],
           [7.82045529e-01, 9.66599933e-01, 1.15904463e-01, ...,
            8.98179810e-01, 2.36312227e-01, 5.97332438e-02],
           [6.58207787e-01, 2.49213187e-01, 1.74473608e-01, ...,
            8.74468364e-01, 3.89589998e-01, 7.56240913e-01],
           ...,
           [2.81427770e-01, 6.41163328e-01, 8.19140151e-01, ...,
            4.25852702e-01, 2.25233268e-01, 7.25609713e-02],
           [1.55249795e-01, 4.63139154e-01, 8.58603912e-01, ...,
            2.93022036e-01, 3.56843074e-02, 1.20851548e-02],
           [9.26646001e-01, 2.66760374e-02, 3.12013449e-01, ...,
            5.22058136e-01, 5.84843390e-01, 3.14280275e-01]],

          [[2.59431725e-01, 8.51521098e-01, 8.36869025e-01, ...,
            9.41991904e-01, 5.86417958e-01, 3.28053321e-01],
           [8.60952378e-01, 2.84515124e-01, 5.78844132e-01, ...,
            9.29320800e-01, 7.98114

Обратите внимание, что обычно форму массивов мы задавали в функциях NumPy одним числом или кортежем, а не перечисляли её в виде аргументов через запятую.

Если передать в rand кортеж, возникнет ошибка:

In [6]:
shape = (3, 4)
np.random.rand(shape)
# TypeError: 'tuple' object cannot be interpreted as an integer
# Ошибка типов: кортеж не может быть интерпретирован как целое число.

TypeError: 'tuple' object cannot be interpreted as an integer

Конечно, можно было бы распаковать кортеж, чтобы избавиться от ошибки:

In [7]:
shape = (3, 4)
np.random.rand(*shape)
# array([[0.66169176, 0.19455777, 0.06451088, 0.31919608],
#        [0.73536951, 0.67104408, 0.4762727 , 0.88153576],
#        [0.70672971, 0.96677145, 0.09273995, 0.86356465]])

array([[0.22130889, 0.29374294, 0.71467822, 0.64655164],
       [0.27964737, 0.2091546 , 0.0486735 , 0.96987726],
       [0.33897664, 0.42598882, 0.87085711, 0.20270674]])

Но в NumPy есть и другая функция, генерирующая массивы случайных чисел от 0 до 1, которая принимает в качестве аргумента именно кортеж без распаковки. Она называется sample:

In [8]:
shape = (2, 3)
np.random.sample(shape)
# array([[0.39756103, 0.01995168, 0.2768951 ],
#       [0.82195372, 0.26435273, 0.00957881]])

array([[0.34740863, 0.22673259, 0.64923037],
       [0.3368193 , 0.61227346, 0.49139953]])

    Возможно, именно функция sample покажется вам удобнее, поскольку информацию о форме массива обычно удобнее хранить в коде в виде кортежа и не задумываться потом о его распаковке. В остальном функция sample не отличается от rand.

Не всегда требуются числа в диапазоне именно от 0 до 1. На самом деле с помощью специальных формул можно из диапазона от 0 до 1 получить любой другой желаемый диапазон, однако это не требуется делать самостоятельно — в NumPy доступна функция uniform:

    uniform(low=0.0, high=1.0, size=None)

Запуск без аргументов эквивалентен работе функций rand или sample:

In [12]:
np.random.uniform()
# 0.951557685543591

0.8149710819496878

Зададим границы диапазона от -30 до 50:

In [13]:
np.random.uniform(-30, 50)
# 38.47365525953661

21.405419943351006

Получим пять чисел в интервале от 0.5 до 0.75:

In [14]:
np.random.uniform(0.5, 0.75, size=5)
# array([0.58078945, 0.58860342, 0.73790553, 0.63448265, 0.70920297])

array([0.58899538, 0.58484721, 0.66054901, 0.74717847, 0.68982403])

Получим массив из двух строк и трёх столбцов из чисел в интервале от -1000 до 500:

In [15]:
np.random.uniform(-1000, 500, size=(2, 3))
# array([[ 129.22164163,   77.69090611, -132.9656972 ],
#        [  18.65802226, -317.14793906,   85.3613547 ]])

array([[-311.73624512, -356.21032848,  412.83954653],
       [-843.62513236,   54.84467952,  337.34273131]])

## Генерация int

Не всегда требуется генерировать числа с плавающей точкой. Иногда бывает удобно получить целые числа int (например, для поля игры в лото). Для генерации целых чисел используется функция random.randint:

    randint(low, high=None, size=None, dtype=int)

Функцию randint нельзя запустить совсем без параметров, необходимо указать хотя бы одно число.

        Если указан только аргумент low, числа будут генерироваться от 0 до low-1, то есть верхняя граница не включается.
        Если задать low и high, числа будут генерироваться от low (включительно) до high (не включительно).
        size задаёт форму массива уже привычным для вас образом: одним числом — для одномерного или кортежем — для многомерного.
        dtype позволяет задать конкретный тип данных, который должен быть использован в массиве.


Сгенерируем таблицу 2x3 от 0 до 3 включительно:

In [16]:
np.random.randint(4, size=(2,3))
# array([[3, 0, 1],
#       [2, 1, 3]])

array([[3, 3, 1],
       [0, 1, 1]])

Чтобы задать и нижнюю, и верхнюю границы самостоятельно, передадим два числа, а затем форму:

In [17]:
np.random.randint(6, 12, size=(3,3))
# array([[ 9,  6, 10],
#        [10, 11, 10],
#        [ 7, 10, 11]])

array([[ 6, 11, 11],
       [ 9, 11,  8],
       [ 7, 11,  8]])

## Генерация выборок

    → Случайные числа можно использовать и для работы с уже существующими данными. Иногда для проверки гипотез о данных бывает удобно перемешать значения, чтобы проверить, является ли наблюдаемая закономерность случайной.

    Просто перемешать все числа в массиве позволяет функция random.shuffle.

    Вспомните, во многих сервисах для прослушивания музыки есть функция shuffle для перемешивания композиций в плейлисте.

Возьмём массив из целых чисел от 0 до 5 и перемешаем его:

In [18]:
arr = np.arange(6)
print(arr)
# [0 1 2 3 4 5]
print(np.random.shuffle(arr))
# None
arr
# array([0, 5, 1, 3, 2, 4])

[0 1 2 3 4 5]
None


array([1, 0, 5, 3, 2, 4])

    Функция random.shuffle перемешивает тот массив, к которому применяется, и возвращает None.

    Чтобы получить новый перемешанный массив, а исходный оставить без изменений, можно использовать функцию random.permutation. Она принимает на вход один аргумент — или массив целиком, или одно число:

In [19]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)
# ['The Beatles' 'Pink Floyd' 'Deep Purple' 'ACDC']
print(playlist)
# ['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']

['Deep Purple' 'Pink Floyd' 'The Beatles' 'ACDC']
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


    Обратите внимание, что необязательно передавать в функцию сразу массив: в этот раз мы передали в качестве аргумента список и ошибки не возникло. При этом на выходе получился уже NumPy-массив (это заметно по отсутствию запятых при печати массива). Сам список playlist при этом остался без изменений.

Перемешать набор чисел от 0 до n-1 можно с помощью записи np.random.permutation(n), где n — верхняя граница, которая бы использовалась для генерации набора чисел функцией arange.

In [20]:
np.random.permutation(10)
# array([7, 8, 2, 9, 4, 3, 1, 0, 5, 6])

array([4, 6, 0, 8, 9, 3, 2, 1, 5, 7])

Перемешать набор чисел от 0 до n-1 можно с помощью записи np.random.permutation(n), где n — верхняя граница, которая бы использовалась для генерации набора чисел функцией arange.

In [21]:
np.random.permutation(10)
# array([7, 8, 2, 9, 4, 3, 1, 0, 5, 6])

array([9, 2, 5, 6, 4, 0, 1, 8, 3, 7])

    Чтобы получить случайный набор объектов из массива, используется функция random.choice:

    choice(a, size=None, replace=True)



        a — одномерный массив или число для генерации arange(a);
        size — желаемая форма массива (число для получения одномерного массива, кортеж — для многомерного; если параметр не задан, возвращается один объект);
        replace — параметр, задающий, могут ли элементы повторяться (по умолчанию могут).


Выберем случайным образом из списка двоих человек, которые должны будут выступить с отчётом на этой неделе. Для этого из списка имён (опять же, можно передавать в функцию choice не NumPy-массив, а список) получим два случайных объекта без повторений (логично, что нужно выбрать двух разных людей). Сделать это можно вот так:

In [22]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
 
choice = np.random.choice(workers, size=2, replace=False)
print(choice)

['Ivan' 'Kate']


Если попытаться получить без повторений массив большего размера, чем имеется объектов в исходном, возникнет ошибка:

In [24]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
choice = np.random.choice(workers, size=10, replace=False)
print(choice)
# ValueError: Cannot take a larger sample than population when 'replace=False'
# Ошибка значения: нельзя получить выборку больше, чем популяция (популяция —
# весь доступный набор объектов, из которого получаем выборку),
# если replace=False (то есть выборка без повторений).

ValueError: Cannot take a larger sample than population when 'replace=False'

    Выборка с повторениями используется по умолчанию. Она применяется в том случае, когда мы допускаем, что объекты могут повторяться.

Например, получим случайную последовательность, которая образуется в результате десяти подбрасываний игральной кости:

In [25]:
choice = np.random.choice([1,2,3,4,5,6], size=10)
print(choice)
# [3 5 5 6 6 4 2 2 1 3]

[6 1 5 2 2 4 4 6 3 4]


## Seed генератора псевдослучайных чисел

    → Как уже было сказано ранее, NumPy генерирует не истинные случайные числа (такие числа получаются в результате случайных процессов), а псевдослучайные, которые получаются с помощью особых преобразований какого-либо исходного числа. Обычно компьютер берёт это число автоматически, например, из текущего времени в микросекундах (на самом деле используются другие ещё менее предсказуемые числа). Такое число называют seed (от англ. — «зерно»).

Самостоятельно задать seed в NumPy можно с помощью функции np.random.seed(<np.uint32>). Число в скобках должно быть в пределах от 0 до 2**32 - 1 (=4294967295).

Зададим seed и посмотрим, что получится:

In [26]:
np.random.seed(23)
np.random.randint(10, size=(3,4))
# array([[3, 6, 8, 9],
#        [6, 8, 7, 9],
#        [3, 6, 1, 2]])

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

Если вы запустите этот код на своём компьютере, то, скорее всего, увидите тот же самый набор чисел!

In [27]:
np.random.seed(100)
print(np.random.randint(10, size=3))
# [8 8 3]
print(np.random.randint(10, size=3))
# [7 7 0]
print(np.random.randint(10, size=3))
# [4 2 5]

[8 8 3]
[7 7 0]
[4 2 5]


## Задание 9.6

Задайте seed = 2021.

Сохраните в переменные необходимые значения.

Примечание 1. Не меняйте названия переменных и последовательность генерации случайных чисел в задании.

Примечание 2. Не забудьте импортировать numpy и сразу задать seed = 2021

1. В simple сохранте случайное число в диапазоне от 0 до 1

2. Сгенерируйте 120 чисел в диапазоне от -150 до 2021, сохраните их в переменную randoms

3. Получите массив из случайных целых чисел от 1 до 100 (включительно) из 3 строк и 2 столбцов. Сохраните результат в table

4. В переменную even сохраните четные числа от 2 до 16 (включительно)

5. Скопируйте even в переменную mix. Перемешайте числа в mix так, чтобы массив изменился

6. Получите из even 3 числа без повторений. Сохраните их в переменную select

7. Получите переменную triplet, которая должна содержать перемешанные значения из массива select (сам select измениться не должен)


In [35]:
import numpy as np

np.random.seed(2021)

In [40]:
# В simple сохранте случайное число в диапазоне от 0 до 1
simple = np.random.rand()

In [41]:
# Сгенерируйте 120 чисел в диапазоне от -150 до 2021, сохраните их
# в переменную randoms
randoms = np.random.uniform(-150, 2021, size=120)

In [42]:
# Получите массив из случайных целых чисел от 1 до 100 (включительно)
# из 3 строк и 2 столбцов. Сохраните результат в table
table = np.random.randint(1, 101, size=(3,2))

In [43]:
# В переменную even сохраните четные числа от 2 до 16 (включительно)
even = np.arange(2,17,2)

In [44]:
# Скопируйте even в переменную mix. Перемешайте числа в mix так, чтобы массив mix изменился
mix = even
np.random.shuffle(mix)

In [45]:
# Получите из even 3 числа без повторений. Сохраните их в переменную select
select = np.random.choice(even, replace=False, size=3)

In [46]:
# Получите переменную triplet, которая должна содержать перемешанные
# значения из массива select (сам select измениться не должен)
triplet = np.random.permutation(select)